[package]
name = "athena"
version = "0.1.0"
edition = "2021"


[dependencies]
patternfly-yew = "0.6.3"
yew = { version = "0.21", features = ["csr"] }
yew-router = "0.18.0"
talaria = { path = "../talaria" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
gloo-net = "0.6.0"
wasm-bindgen-futures = "0.4.49"
gloo-timers = "0.3.0"
chrono = "0.4.39"

[dependencies.web-sys]
version = "0.3"
features = [
    "HtmlElement",
    "HtmlInputElement",
    "MediaQueryList",
    "Window",
    "Location",
    "UrlSearchParams",
]
