name: Build All

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.12.2

      - name: Install Dioxus Dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          packages: libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev
          version: 1.0
            
      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Install Dioxus CLI
        run: cargo binstall dioxus-cli
      
      - name: Install Node.js and TailwindCSS CLI
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Tailwind styles for Athena
        run: |
          cd athena
          npx @tailwindcss/cli -i input.css -o assets/tailwind.css


      - name: Build Athena (Web)
        run: |
          cd athena
          dx build --release --output ../athena-web-dist

      - name: Build Athena (Desktop)
        run: |
          cd athena
          dx build --platform desktop --release

      - name: Build Hermes
        run: |
          cd hermes
          cargo build --release --out-dir ../hermes-bin

      - name: Build Tartarus
        run: |
          cd tartarus
          cargo build --release --out-dir ../tartarus-bin

      - name: Upload Athena Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: athena-web-build
          path: target/dx/athena/release/web/public

      - name: Upload Athena Desktop Artifact
        uses: actions/upload-artifact@v4
        with:
          name: athena-desktop-build
          path: target/dx/athena/release/linux/app

      - name: Upload Hermes Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hermes-binary
          path: hermes-bin/

      - name: Upload Tartarus Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tartarus-binary
          path: tartarus-bin/
